// <auto-generated />
namespace Bow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class update_table_preguntasFrecuentes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_table_preguntasFrecuentes));
        
        string IMigrationMetadata.Id
        {
            get { return "201507130325493_update_table_preguntasFrecuentes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
