// <auto-generated />
namespace Bow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class changes_apiary_web_services : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes_apiary_web_services));
        
        string IMigrationMetadata.Id
        {
            get { return "201507140105448_changes_apiary_web_services"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
