// <auto-generated />
namespace Bow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class drop_table_diagnostico : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(drop_table_diagnostico));
        
        string IMigrationMetadata.Id
        {
            get { return "201507140214234_drop_table_diagnostico"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
