// <auto-generated />
namespace Bow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class add_tables_diagnostico_historiaVial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_tables_diagnostico_historiaVial));
        
        string IMigrationMetadata.Id
        {
            get { return "201507130609555_add_tables_diagnostico_historiaVial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
